# Imports

In [1]:
import re
import optuna
import pickle

import numpy as np
import pandas as pd

from sklearn import set_config
from catboost import CatBoostClassifier

from sklearn.pipeline import make_pipeline
from sklearn.metrics import roc_auc_score
from sklearn.ensemble import StackingClassifier, VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedKFold, cross_val_predict

from feature_engine.selection import DropFeatures

/home/junior/Documentos/GitHub/prediction-f1-pit-stops-kaggle-competition/.venv/lib/python3.13/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

## Utils

In [2]:
set_config(enable_metadata_routing=True)

In [3]:
def load_pickle(file_path):
    with open(file_path, 'rb') as file:
        return pickle.load(file)

# Loading Dataset

In [4]:
X_train = pd.read_parquet('../data/X_train.parquet')
X_test = pd.read_parquet('../data/X_test.parquet')

y_train = pd.read_parquet('../data/y_train.parquet')

In [5]:
X_train.head()

,driver,compound,race,year,pitstop,lapnumber,stint,tyrelife,position,laptime_s,...,treeraceprogress,treeposition,treelaptime_s,treecumulative_degradation,treeraceprogress_position,treeraceprogress_laptime_s,treeraceprogress_cumulative_degradation,treeposition_laptime_s,treeposition_cumulative_degradation,treelaptime_s_cumulative_degradation
id,,,,,,,,,,,,,,,,,,,,,
0,D109,HARD,Canadian Grand Prix,2022,0,50,2,39.0,8,78.491,...,0.298107,0.207392,0.252153,0.279021,0.298107,0.298107,0.321361,0.252153,0.279021,0.253721
1,D086,HARD,Dutch Grand Prix,2025,1,27,2,7.0,4,75.095,...,0.298107,0.185508,0.252153,0.586119,0.298107,0.298107,0.610176,0.252153,0.544023,0.613159
2,ZON,HARD,Austrian Grand Prix,2022,0,59,3,22.0,13,70.945,...,0.298107,0.207392,0.252153,0.207676,0.298107,0.298107,0.423519,0.252153,0.228194,0.231339
3,SPE,MEDIUM,Pre-Season Testing,2023,0,2,1,2.0,7,94.361,...,0.102471,0.185508,0.178575,0.138352,0.102471,0.102471,0.043550,0.178575,0.138352,0.070991
4,D019,HARD,Azerbaijan Grand Prix,2022,1,26,3,6.0,2,107.878,...,0.298107,0.185508,0.178575,0.138352,0.298107,0.298107,0.206543,0.178575,0.138352,0.153276

In [6]:
X_test.head()

,driver,compound,race,year,pitstop,lapnumber,stint,tyrelife,position,laptime_s,...,treeraceprogress,treeposition,treelaptime_s,treecumulative_degradation,treeraceprogress_position,treeraceprogress_laptime_s,treeraceprogress_cumulative_degradation,treeposition_laptime_s,treeposition_cumulative_degradation,treelaptime_s_cumulative_degradation
id,,,,,,,,,,,,,,,,,,,,,
439140,D119,MEDIUM,British Grand Prix,2023,0,21,1,21.0,4,93.387,...,0.298107,0.185508,0.178575,0.138352,0.298107,0.298107,0.206543,0.178575,0.138352,0.070991
439141,VER,MEDIUM,Abu Dhabi Grand Prix,2023,0,24,1,24.0,1,90.867,...,0.298107,0.185508,0.178575,0.147360,0.298107,0.298107,0.321361,0.178575,0.147360,0.253721
439142,D270,MEDIUM,British Grand Prix,2023,0,24,1,24.0,11,92.871,...,0.298107,0.207392,0.178575,0.138352,0.298107,0.298107,0.206543,0.178575,0.138352,0.070991
439143,D112,SOFT,São Paulo Grand Prix,2024,0,6,2,4.0,15,94.967,...,0.102471,0.207392,0.178575,0.279021,0.102471,0.102471,0.071042,0.178575,0.279021,0.216120
439144,AND,HARD,United States Grand Prix,2024,0,52,2,29.0,12,99.112,...,0.298107,0.207392,0.178575,0.111582,0.298107,0.298107,0.206543,0.178575,0.111582,0.216120

## Creating Stacking Database

In [7]:
lgbm = load_pickle('../models/model_lightgbm.pkl')
cat = load_pickle('../models/model_pure_catboost.pkl')
catencoder_cat = load_pickle('../models/model_catboostencoder_catboost.pkl')
xgb = load_pickle('../models/model_xgboost.pkl')
hist = load_pickle('../models/model_histgradientboosting.pkl')
lg = load_pickle('../models/model_logistic_regression.pkl')
voting = load_pickle('../models/model_voting.pkl')

In [ ]:
cv = StratifiedKFold(shuffle=True, random_state=42, n_splits=5)

lgbm_proba = cross_val_predict(lgbm, X_train, y_train.PitNextLap, cv=cv, n_jobs=-1, method='predict_proba')[:, 1]
catencoder_cat_proba = cross_val_predict(catencoder_cat, X_train, y_train.PitNextLap, cv=cv, n_jobs=-1, method='predict_proba')[:, 1]
xgb_proba = cross_val_predict(xgb, X_train, y_train.PitNextLap, cv=cv, n_jobs=-1, method='predict_proba')[:, 1]
hist_proba = cross_val_predict(hist, X_train, y_train.PitNextLap, cv=cv, n_jobs=-1, method='predict_proba')[:, 1]
lg_proba = cross_val_predict(lg, X_train, y_train.PitNextLap, cv=cv, n_jobs=-1, method='predict_proba')[:, 1]
voting_proba = cross_val_predict(voting, X_train, y_train.PitNextLap, cv=cv, n_jobs=-1, method='predict_proba',)[:, 1]

cat_proba = cross_val_predict(
    make_pipeline(
        DropFeatures(['treelaptime_s', 'treeraceprogress_position', 'treeposition_laptime_s']),
        CatBoostClassifier(
            loss_function='Logloss',
            eval_metric='AUC',
            auto_class_weights="Balanced",
            verbose=0,
            thread_count=1
        )
    ), 
    X_train, 
    y_train.PitNextLap,
    cv=cv, 
    n_jobs=-1, 
    method='predict_proba',
    params={'catboostclassifier__cat_features': ['driver', 'compound', 'race']}
)[:, 1]

In [ ]:
X_train_stacking = pd.DataFrame({
    'lgbm_proba': lgbm_proba,
    'catencoder_cat_proba': catencoder_cat_proba,
    'xgb_proba': xgb_proba,
    'hist_proba': hist_proba,
    'lg_proba': lg_proba,
    'voting_proba': voting_proba,
    'cat_proba': cat_proba
})

X_train_stacking.to_parquet('../data/X_train_stacking.parquet')

In [ ]:
X_test_stacking = pd.DataFrame({
    'lgbm_proba': lgbm.predict_proba(X_test)[:, 1],
    'catencoder_cat_proba': catencoder_cat.predict_proba(X_test)[:, 1],
    'xgb_proba': xgb.predict_proba(X_test)[:, 1],
    'hist_proba': hist.predict_proba(X_test)[:, 1],
    'lg_proba': lg.predict_proba(X_test)[:, 1],
    'voting_proba': voting.predict_proba(X_test)[:, 1],
    'cat_proba': cat.predict_proba(X_test)[:, 1]
})

X_test_stacking.to_parquet('../data/X_test_stacking.parquet')

# Machine Learning

In [52]:
def objective(trial, X, y):

    cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

    aucs = []

    params = {
        "solver": trial.suggest_categorical("solver", ["saga"]),
        "C": trial.suggest_float("C", 1e-5, 100, log=True),
        "l1_ratio": trial.suggest_float("l1_ratio", 0.0, 1.0),
        "class_weight": trial.suggest_categorical("class_weight", [None, "balanced"]),
        "fit_intercept": trial.suggest_categorical("fit_intercept", [True, False]),
        "tol": trial.suggest_float("tol", 1e-6, 1e-2, log=True),
        "max_iter": trial.suggest_int("max_iter", 1000, 5000),
        "random_state": trial.suggest_int("random_state", 0, 1000)
    }

    for fold, (train_idx, valid_idx) in enumerate(cv.split(X, y)):

        X_train, X_valid = X.iloc[train_idx, :], X.iloc[valid_idx, :]
        y_train, y_valid = y.iloc[train_idx, 0], y.iloc[valid_idx, 0]

        model = LogisticRegression(**params)
        model.fit(X_train, y_train)

        proba = model.predict_proba(X_valid)[:, 1]

        auc = roc_auc_score(y_valid, proba)
        aucs.append(auc)

        trial.report(np.mean(aucs), step=fold)

        if trial.should_prune():
            raise optuna.exceptions.TrialPruned()

    return np.mean(aucs)


study = optuna.create_study(direction="maximize", sampler=optuna.samplers.TPESampler(seed=42), pruner=optuna.pruners.MedianPruner(n_warmup_steps=2))
study.optimize(lambda trial: objective(trial, X_stacking, y_train), n_trials=500, n_jobs=-1)


print("Best trial score:")
print(study.best_trial.value)

print("\nBest params:")
print(study.best_trial.params)

[I 2026-05-13 12:12:35,144] A new study created in memory with name: no-name-76bf0235-cb5b-4921-a539-94e80a1f6edb
[I 2026-05-13 12:12:38,952] Trial 9 finished with value: 0.5 and parameters: {'solver': 'saga', 'C': 1.6473915438563915e-05, 'l1_ratio': 0.9122264251617757, 'class_weight': None, 'fit_intercept': False, 'tol': 2.5810005378995377e-05, 'max_iter': 4153, 'random_state': 334}. Best is trial 9 with value: 0.5.
[I 2026-05-13 12:12:41,191] Trial 7 finished with value: 0.5 and parameters: {'solver': 'saga', 'C': 1.1823904139199353e-05, 'l1_ratio': 0.8238443705178026, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0017001359671289836, 'max_iter': 1418, 'random_state': 400}. Best is trial 9 with value: 0.5.
[I 2026-05-13 12:12:45,542] Trial 1 finished with value: 0.7881533219107638 and parameters: {'solver': 'saga', 'C': 0.11744159885812057, 'l1_ratio': 0.9401668857519256, 'class_weight': None, 'fit_intercept': False, 'tol': 0.003412336600702748, 'max_iter': 4596, 'random_state': 746}. Best is trial 1 with value: 0.7881533219107638.
[I 2026-05-13 12:12:48,500] Trial 6 finished with value: 0.94981408678932 and parameters: {'solver': 'saga', 'C': 1.7887176002968224, 'l1_ratio': 0.41396851389052924, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0074347900676728544, 'max_iter': 4539, 'random_state': 104}. Best is trial 6 with value: 0.94981408678932.
[I 2026-05-13 12:12:52,430] Trial 3 finished with value: 0.9497075539556068 and parameters: {'solver': 'saga', 'C': 9.44281734943159e-05, 'l1_ratio': 0.7975244125339569, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00042503121858505606, 'max_iter': 1513, 'random_state': 546}. Best is trial 6 with value: 0.94981408678932.
[I 2026-05-13 12:12:53,062] Trial 12 finished with value: 0.9491259972171899 and parameters: {'solver': 'saga', 'C': 0.00029378629448514393, 'l1_ratio': 0.15190036300195664, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0009641630881209157, 'max_iter': 2844, 'random_state': 286}. Best is trial 6 with value: 0.94981408678932.
[I 2026-05-13 12:12:54,054] Trial 8 pruned.
[I 2026-05-13 12:12:54,244] Trial 5 finished with value: 0.9497300138767697 and parameters: {'solver': 'saga', 'C': 79.22404431269757, 'l1_ratio': 0.6043623018816894, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0012684287837689797, 'max_iter': 2753, 'random_state': 170}. Best is trial 6 with value: 0.94981408678932.
[I 2026-05-13 12:12:55,368] Trial 10 finished with value: 0.949826916518516 and parameters: {'solver': 'saga', 'C': 6.767591255545379e-05, 'l1_ratio': 0.33608435486098465, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 9.681694550468553e-05, 'max_iter': 2059, 'random_state': 273}. Best is trial 10 with value: 0.949826916518516.
[I 2026-05-13 12:12:56,288] Trial 14 pruned.
[I 2026-05-13 12:12:56,652] Trial 13 finished with value: 0.9497302294115322 and parameters: {'solver': 'saga', 'C': 0.6983763385012071, 'l1_ratio': 0.6855447667627317, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0023108174795809745, 'max_iter': 4370, 'random_state': 800}. Best is trial 10 with value: 0.949826916518516.
[I 2026-05-13 12:12:56,905] Trial 11 pruned.
[I 2026-05-13 12:12:57,622] Trial 4 finished with value: 0.9497304374645662 and parameters: {'solver': 'saga', 'C': 1.3051895571005903, 'l1_ratio': 0.09452118034459722, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 8.133535812525526e-05, 'max_iter': 1286, 'random_state': 648}. Best is trial 10 with value: 0.949826916518516.
[I 2026-05-13 12:12:57,703] Trial 0 finished with value: 0.9491527357989609 and parameters: {'solver': 'saga', 'C': 3.241396865029106e-05, 'l1_ratio': 0.3521269306055357, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.00012179178333325812, 'max_iter': 1812, 'random_state': 310}. Best is trial 10 with value: 0.949826916518516.
[I 2026-05-13 12:12:58,221] Trial 19 pruned.
[I 2026-05-13 12:13:01,910] Trial 25 pruned.
[I 2026-05-13 12:13:02,094] Trial 23 pruned.
[I 2026-05-13 12:13:02,214] Trial 15 finished with value: 0.9498137847450294 and parameters: {'solver': 'saga', 'C': 64.78695682775134, 'l1_ratio': 0.328800901144667, 'class_weight': None, 'fit_intercept': True, 'tol': 0.006431087967855145, 'max_iter': 2426, 'random_state': 271}. Best is trial 10 with value: 0.949826916518516.
[I 2026-05-13 12:13:03,049] Trial 26 pruned.
[I 2026-05-13 12:13:03,999] Trial 2 finished with value: 0.9498164094457264 and parameters: {'solver': 'saga', 'C': 0.24967612205194406, 'l1_ratio': 0.04334326315448023, 'class_weight': None, 'fit_intercept': True, 'tol': 3.3387400860101892e-06, 'max_iter': 2060, 'random_state': 370}. Best is trial 10 with value: 0.949826916518516.
[I 2026-05-13 12:13:06,053] Trial 17 pruned.
[I 2026-05-13 12:13:08,244] Trial 18 finished with value: 0.9497304579680816 and parameters: {'solver': 'saga', 'C': 24.12089289676005, 'l1_ratio': 0.28455338705803124, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 0.0075309209527291985, 'max_iter': 3545, 'random_state': 66}. Best is trial 10 with value: 0.949826916518516.
[I 2026-05-13 12:13:08,979] Trial 20 finished with value: 0.9498183730368854 and parameters: {'solver': 'saga', 'C': 0.12643329063848663, 'l1_ratio': 0.1796562427128019, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0031721989022290196, 'max_iter': 2559, 'random_state': 319}. Best is trial 10 with value: 0.949826916518516.
[I 2026-05-13 12:13:09,405] Trial 22 pruned.
[I 2026-05-13 12:13:12,705] Trial 28 pruned.
[I 2026-05-13 12:13:13,363] Trial 30 pruned.
[I 2026-05-13 12:13:13,444] Trial 29 pruned.
[I 2026-05-13 12:13:14,241] Trial 24 pruned.
[I 2026-05-13 12:13:14,246] Trial 27 pruned.
[I 2026-05-13 12:13:14,492] Trial 21 pruned.
[I 2026-05-13 12:13:21,451] Trial 16 finished with value: 0.9498347548281725 and parameters: {'solver': 'saga', 'C': 5.388397889385867e-05, 'l1_ratio': 0.6462432720664458, 'class_weight': 'balanced', 'fit_intercept': False, 'tol': 7.474375772577232e-06, 'max_iter': 1875, 'random_state': 50}. Best is trial 16 with value: 0.9498347548281725.
[I 2026-05-13 12:13:22,649] Trial 31 pruned.
[I 2026-05-13 12:13:25,418] Trial 32 finished with value: 0.9498138223239403 and parameters: {'solver': 'saga', 'C': 17.68915106551413, 'l1_ratio': 0.0072638459605109396, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00036501619530284607, 'max_iter': 2247, 'random_state': 167}. Best is trial 16 with value: 0.9498347548281725.
[I 2026-05-13 12:13:26,076] Trial 34 finished with value: 0.9498345495495798 and parameters: {'solver': 'saga', 'C': 0.022344262280271348, 'l1_ratio': 0.2303425351116806, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0003649142115339736, 'max_iter': 2297, 'random_state': 413}. Best is trial 16 with value: 0.9498347548281725.
[I 2026-05-13 12:13:37,250] Trial 37 finished with value: 0.9498237806813773 and parameters: {'solver': 'saga', 'C': 0.03617750905608968, 'l1_ratio': 0.014716474404537938, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4639186847465353e-05, 'max_iter': 1038, 'random_state': 435}. Best is trial 16 with value: 0.9498347548281725.
[I 2026-05-13 12:13:37,325] Trial 39 finished with value: 0.9498241876782046 and parameters: {'solver': 'saga', 'C': 0.033815785518784926, 'l1_ratio': 0.01166471576340583, 'class_weight': None, 'fit_intercept': True, 'tol': 2.5441926277868886e-05, 'max_iter': 1735, 'random_state': 416}. Best is trial 16 with value: 0.9498347548281725.
[I 2026-05-13 12:13:38,328] Trial 40 finished with value: 0.9498277159621041 and parameters: {'solver': 'saga', 'C': 0.021786835627817483, 'l1_ratio': 0.018567162788590035, 'class_weight': None, 'fit_intercept': True, 'tol': 2.570003995470407e-05, 'max_iter': 1038, 'random_state': 998}. Best is trial 16 with value: 0.9498347548281725.
[I 2026-05-13 12:13:39,637] Trial 33 finished with value: 0.9498139155335711 and parameters: {'solver': 'saga', 'C': 5.773057527894235, 'l1_ratio': 0.005678245794328948, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3863972059116517e-06, 'max_iter': 4972, 'random_state': 151}. Best is trial 16 with value: 0.9498347548281725.
[I 2026-05-13 12:13:39,780] Trial 41 finished with value: 0.949826283500731 and parameters: {'solver': 'saga', 'C': 0.02549844954057523, 'l1_ratio': 0.020211387050266677, 'class_weight': None, 'fit_intercept': True, 'tol': 6.926082563300612e-06, 'max_iter': 1787, 'random_state': 995}. Best is trial 16 with value: 0.9498347548281725.
[I 2026-05-13 12:13:40,753] Trial 35 finished with value: 0.949813913581548 and parameters: {'solver': 'saga', 'C': 5.666956443365601, 'l1_ratio': 0.013861678007673808, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3568920533626584e-06, 'max_iter': 2303, 'random_state': 423}. Best is trial 16 with value: 0.9498347548281725.
[I 2026-05-13 12:13:41,706] Trial 36 finished with value: 0.9498245992279102 and parameters: {'solver': 'saga', 'C': 0.030180620653839883, 'l1_ratio': 0.0032947436071713854, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6653388503905752e-06, 'max_iter': 2444, 'random_state': 434}. Best is trial 16 with value: 0.9498347548281725.
[I 2026-05-13 12:13:43,697] Trial 38 finished with value: 0.9498292406691113 and parameters: {'solver': 'saga', 'C': 0.028131363498710312, 'l1_ratio': 0.15741042234613212, 'class_weight': None, 'fit_intercept': True, 'tol': 1.052913288943841e-06, 'max_iter': 3117, 'random_state': 421}. Best is trial 16 with value: 0.9498347548281725.
[I 2026-05-13 12:13:45,495] Trial 42 finished with value: 0.9498241528678715 and parameters: {'solver': 'saga', 'C': 0.03735624303249384, 'l1_ratio': 0.04819256495351877, 'class_weight': None, 'fit_intercept': True, 'tol': 1.4637510440372743e-05, 'max_iter': 1764, 'random_state': 425}. Best is trial 16 with value: 0.9498347548281725.
[I 2026-05-13 12:13:46,549] Trial 43 finished with value: 0.9498442727833887 and parameters: {'solver': 'saga', 'C': 0.02152714960941191, 'l1_ratio': 0.49013864424813974, 'class_weight': None, 'fit_intercept': True, 'tol': 1.3589706314973636e-05, 'max_iter': 1807, 'random_state': 226}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:13:48,372] Trial 45 finished with value: 0.9498351369400438 and parameters: {'solver': 'saga', 'C': 0.032917294582972406, 'l1_ratio': 0.5077940437397099, 'class_weight': None, 'fit_intercept': True, 'tol': 2.8556544985511945e-05, 'max_iter': 1749, 'random_state': 233}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:13:48,650] Trial 44 finished with value: 0.9498339964639385 and parameters: {'solver': 'saga', 'C': 0.03400868578897572, 'l1_ratio': 0.47867283850509856, 'class_weight': None, 'fit_intercept': True, 'tol': 2.1132451523858277e-05, 'max_iter': 1742, 'random_state': 234}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:13:58,482] Trial 48 finished with value: 0.9497774212772017 and parameters: {'solver': 'saga', 'C': 0.00024361261985600245, 'l1_ratio': 0.6964129938026116, 'class_weight': None, 'fit_intercept': True, 'tol': 5.1355385916347915e-05, 'max_iter': 1757, 'random_state': 994}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:13:59,107] Trial 47 finished with value: 0.9494380015873414 and parameters: {'solver': 'saga', 'C': 0.00016906481849458512, 'l1_ratio': 0.47515979215640036, 'class_weight': None, 'fit_intercept': True, 'tol': 4.001161204386924e-05, 'max_iter': 1715, 'random_state': 234}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:13:59,686] Trial 50 finished with value: 0.9495170903168763 and parameters: {'solver': 'saga', 'C': 0.0003128942074003839, 'l1_ratio': 0.49578816511705326, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 4.944501907159153e-05, 'max_iter': 1049, 'random_state': 215}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:00,110] Trial 46 finished with value: 0.9495940301639351 and parameters: {'solver': 'saga', 'C': 0.00038369713571467166, 'l1_ratio': 0.48927068086438763, 'class_weight': None, 'fit_intercept': True, 'tol': 1.9501142980467894e-05, 'max_iter': 1002, 'random_state': 443}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:00,252] Trial 49 finished with value: 0.9495798547482206 and parameters: {'solver': 'saga', 'C': 0.000398164679538622, 'l1_ratio': 0.4731736992569401, 'class_weight': None, 'fit_intercept': True, 'tol': 4.61540712040628e-05, 'max_iter': 1774, 'random_state': 949}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:00,836] Trial 51 finished with value: 0.9494835873923229 and parameters: {'solver': 'saga', 'C': 0.0002550933917937272, 'l1_ratio': 0.49785662617797394, 'class_weight': 'balanced', 'fit_intercept': True, 'tol': 5.0206103410837056e-05, 'max_iter': 1675, 'random_state': 237}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:01,127] Trial 53 finished with value: 0.949582901565605 and parameters: {'solver': 'saga', 'C': 0.0003833778465883979, 'l1_ratio': 0.48129877612302663, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00017922626413731865, 'max_iter': 3103, 'random_state': 589}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:01,146] Trial 52 finished with value: 0.9497592156022329 and parameters: {'solver': 'saga', 'C': 0.00013583195855952195, 'l1_ratio': 0.6858813519038018, 'class_weight': None, 'fit_intercept': True, 'tol': 4.623196430580226e-05, 'max_iter': 1790, 'random_state': 989}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:03,753] Trial 54 finished with value: 0.9497846132338303 and parameters: {'solver': 'saga', 'C': 0.00031333553514480936, 'l1_ratio': 0.6951024345365372, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0001864208087815036, 'max_iter': 3023, 'random_state': 589}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:09,832] Trial 57 finished with value: 0.949809034869735 and parameters: {'solver': 'saga', 'C': 0.0008768757729489424, 'l1_ratio': 0.6681020828443661, 'class_weight': None, 'fit_intercept': True, 'tol': 5.019848263554556e-05, 'max_iter': 1567, 'random_state': 239}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:10,497] Trial 55 finished with value: 0.9498149914326529 and parameters: {'solver': 'saga', 'C': 0.8035251389473437, 'l1_ratio': 0.6894366787461974, 'class_weight': None, 'fit_intercept': True, 'tol': 3.804792351048659e-05, 'max_iter': 3105, 'random_state': 232}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:16,320] Trial 56 finished with value: 0.949793465895743 and parameters: {'solver': 'saga', 'C': 0.00044568761313720133, 'l1_ratio': 0.6877945105086904, 'class_weight': None, 'fit_intercept': True, 'tol': 2.853016353366558e-06, 'max_iter': 3100, 'random_state': 229}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:16,863] Trial 58 finished with value: 0.9498160424467563 and parameters: {'solver': 'saga', 'C': 0.41340534666115125, 'l1_ratio': 0.5070877430739987, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00017361386926736393, 'max_iter': 1619, 'random_state': 212}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:20,226] Trial 62 finished with value: 0.9498248567038013 and parameters: {'solver': 'saga', 'C': 0.07766193507123882, 'l1_ratio': 0.6031563763661457, 'class_weight': None, 'fit_intercept': True, 'tol': 0.00015561358819366836, 'max_iter': 1529, 'random_state': 342}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:24,362] Trial 59 finished with value: 0.9498161659103717 and parameters: {'solver': 'saga', 'C': 0.4188980957792252, 'l1_ratio': 0.6314510069991377, 'class_weight': None, 'fit_intercept': True, 'tol': 1.1276150065513091e-05, 'max_iter': 1540, 'random_state': 228}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:24,616] Trial 60 finished with value: 0.9498165963350729 and parameters: {'solver': 'saga', 'C': 0.36305038935046724, 'l1_ratio': 0.6652573098214022, 'class_weight': None, 'fit_intercept': True, 'tol': 8.634213566728288e-06, 'max_iter': 1561, 'random_state': 364}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:25,385] Trial 61 finished with value: 0.949816478237253 and parameters: {'solver': 'saga', 'C': 0.3617706404500615, 'l1_ratio': 0.5988702536471715, 'class_weight': None, 'fit_intercept': True, 'tol': 9.449710101722475e-06, 'max_iter': 1965, 'random_state': 601}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:26,067] Trial 63 finished with value: 0.9498155489044509 and parameters: {'solver': 'saga', 'C': 0.5648282861055546, 'l1_ratio': 0.6013438092808208, 'class_weight': None, 'fit_intercept': True, 'tol': 8.99504839495125e-06, 'max_iter': 1972, 'random_state': 368}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:28,118] Trial 68 finished with value: 0.9498242704481484 and parameters: {'solver': 'saga', 'C': 0.07998763285352015, 'l1_ratio': 0.5580315235780882, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006889157941115767, 'max_iter': 1959, 'random_state': 361}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:28,210] Trial 65 finished with value: 0.9498158339017971 and parameters: {'solver': 'saga', 'C': 0.49039237887104914, 'l1_ratio': 0.6079389691232449, 'class_weight': None, 'fit_intercept': True, 'tol': 4.218801285442081e-06, 'max_iter': 1980, 'random_state': 362}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:28,213] Trial 64 finished with value: 0.9498153678528386 and parameters: {'solver': 'saga', 'C': 0.6119871559719962, 'l1_ratio': 0.5641992158606449, 'class_weight': None, 'fit_intercept': True, 'tol': 9.045426098569779e-06, 'max_iter': 1952, 'random_state': 347}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:28,937] Trial 66 finished with value: 0.9498157572846259 and parameters: {'solver': 'saga', 'C': 0.5023277038181784, 'l1_ratio': 0.6002395241140825, 'class_weight': None, 'fit_intercept': True, 'tol': 1.0267864384347614e-05, 'max_iter': 2019, 'random_state': 343}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:33,986] Trial 69 finished with value: 0.9498243719477166 and parameters: {'solver': 'saga', 'C': 0.08342714456040301, 'l1_ratio': 0.6140522105233579, 'class_weight': None, 'fit_intercept': True, 'tol': 0.0006185961454576134, 'max_iter': 1978, 'random_state': 83}. Best is trial 43 with value: 0.9498442727833887.
[I 2026-05-13 12:14:37,143] Trial 67 finished with value: 0.9498615459858971 and parameters: {'solver': 'saga', 'C': 0.010988938509223252, 'l1_ratio': 0.5691045180311837, 'class_weight': None, 'fit_intercept': True, 'tol': 8.793130881296957e-06, 'max_iter': 1974, 'random_state': 355}. Best is trial 67 with value: 0.9498615459858971.
[I 2026-05-13 12:14:37,635] Trial 79 pruned.
[I 2026-05-13 12:14:41,967] Trial 70 finished with value: 0.9498240906935429 and parameters: {'solver': 'saga', 'C': 0.08537408135397989, 'l1_ratio': 0.610634554576533, 'class_weight': None, 'fit_intercept': True, 'tol': 9.038699288475857e-06, 'max_iter': 1960, 'random_state': 351}. Best is trial 67 with value: 0.9498615459858971.
[I 2026-05-13 12:14:44,343] Trial 71 finished with value: 0.9498665533329331 and parameters: {'solver': 'saga', 'C': 0.009808614470298847, 'l1_ratio': 0.7441519599650539, 'class_weight': None, 'fit_intercept': True, 'tol': 8.514242962313117e-06, 'max_iter': 1992, 'random_state': 368}. Best is trial 71 with value: 0.9498665533329331.
[I 2026-05-13 12:14:44,728] Trial 80 pruned.
[I 2026-05-13 12:14:49,045] Trial 81 pruned.

Best trial score:
0.9498706450715897

Best params:
{'solver': 'saga', 'C': 0.01185232258736047, 'l1_ratio': 0.9726417663956377, 'class_weight': None, 'fit_intercept': True, 'tol': 1.6007186630931186e-05, 'max_iter': 1218, 'random_state': 290}

In [55]:
stacking_lg = LogisticRegression(**study.best_params).fit(X_stacking, y_train.PitNextLap)

# Submission

In [56]:
submission = pd.read_csv('../data/sample_submission.csv')

In [57]:
submission['PitNextLap'] = stacking_lg.predict_proba(X_test_stacking)[:, 1]

In [58]:
submission.to_csv('../data/submission.csv', index=False)